import {
  TAccountsGridTemplate,
  TBankAccountsGridTemplate,
  TCustomersGridTemplate,
  TVendorsGridData,
} from './types';

export const accountsGridTemplate: TAccountsGridTemplate[] = [
  {
    title: 'Account No',
    field: 'AccountNo',
    hasColumnMenu: true,
    width: '150',
    classNameStyle: '',
  },
  {
    title: 'Account Name',
    field: 'AccountName',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Account Type',
    field: 'AccountType',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Inactive',
    field: 'InactiveYN',
    hasColumnMenu: true,
    width: '',
    classNameStyle: '',
  },
];

export const bankAccountsGridTemplate: TBankAccountsGridTemplate[] = [
  {
    title: 'Date',
    field: 'TransDate',
    hasColumnMenu: true,
    width: '120',
    classNameStyle: '',
  },
  {
    title: 'Account',
    field: 'TransAccount',
    hasColumnMenu: true,
    width: '100',
    classNameStyle: '',
  },
  {
    title: 'Type',
    field: 'TransTypeDesc',
    hasColumnMenu: true,
    width: '150',
    classNameStyle: '',
  },
  {
    title: 'PMT',
    field: 'TransPmtMethod',
    hasColumnMenu: true,
    width: '100',
    classNameStyle: '',
  },
  {
    title: 'Reference',
    field: 'TransDocRef',
    hasColumnMenu: true,
    width: '150',
    classNameStyle: '',
  },
  {
    title: 'Name',
    field: 'TransEntityName',
    hasColumnMenu: true,
    width: '300',
    classNameStyle: '',
  },
  {
    title: 'C',
    field: 'ChkClearedYN',
    hasColumnMenu: true,
    width: '70',
    classNameStyle: '',
  },
  // {
  //   title: 'V',
  //   field: 'ChkVoidYN',
  //   hasColumnMenu: true,
  //   width: '100',
  //   classNameStyle: '',
  // },
  {
    title: 'Debit',
    field: 'TransDebitAmount',
    hasColumnMenu: true,
    width: '100',
    classNameStyle: 'text-right',
  },
  {
    title: 'Credit',
    field: 'TransCreditAmount',
    hasColumnMenu: true,
    width: '100',
    classNameStyle: 'text-right',
  },
  {
    title: 'Balance',
    field: 'RunningBalance',
    hasColumnMenu: true,
    width: '',
    classNameStyle: 'text-right',
  },
  // {
  //   title: 'Notes',
  //   field: 'Notes',
  //   hasColumnMenu: false,
  //   width: '',
  //   classNameStyle: '',
  // },
];

export const customersGridTemplate: TCustomersGridTemplate[] = [
  {
    title: 'Name',
    field: 'EntityName',
    hasColumnMenu: true,
    width: '325',
    classNameStyle: '',
  },
  {
    title: 'City',
    field: 'City',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'State',
    field: 'State',
    hasColumnMenu: true,
    width: '80',
    classNameStyle: '',
  },
  {
    title: 'Contact',
    field: 'PrimaryContact',
    hasColumnMenu: true,
    width: '120',
    classNameStyle: '',
  },
  {
    title: 'Phone',
    field: 'MainPhone',
    hasColumnMenu: true,
    width: '180',
    classNameStyle: '',
  },
  {
    title: 'Email',
    field: 'EmailMain',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Notes',
    field: 'Notes',
    hasColumnMenu: true,
    width: '',
    classNameStyle: '',
  },
];

export const vendorsGridData: TVendorsGridData[] = [
  {
    title: 'Name',
    field: 'EntityName',
    hasColumnMenu: true,
    width: '325',
    classNameStyle: '',
  },
  {
    title: 'City',
    field: 'City',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'State',
    field: 'State',
    hasColumnMenu: true,
    width: '80',
    classNameStyle: '',
  },
  {
    title: 'Contact',
    field: 'PrimaryContact',
    hasColumnMenu: true,
    width: '120',
    classNameStyle: '',
  },
  {
    title: 'Phone',
    field: 'MainPhone',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Email',
    field: 'EmailMain',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Notes',
    field: 'Notes',
    hasColumnMenu: true,
    width: '',
    classNameStyle: '',
  },
];

export const employeesGridData = [
  {
    title: 'Name',
    field: 'EntityName',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'City',
    field: 'City',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'State',
    field: 'State',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'LocCode',
    field: 'LocCode',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Job Title',
    field: 'JobTitle',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Department',
    field: 'Department',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Phone',
    field: 'MainPhone',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Email',
    field: 'EmailMain',
    hasColumnMenu: true,
    width: '200',
    classNameStyle: '',
  },
  {
    title: 'Notes',
    field: 'Notes',
    hasColumnMenu: true,
    width: '',
    classNameStyle: '',
  },
];
